MODEL: 'sem_seg.pointnet2'
TRAIN:
  BATCH_SIZE: 16
  MAX_EPOCH: 150
  PRETRAINED_MODEL_PATH: 'log/sem_seg_pointnet2_block_pretrain/pretrain.ckpt'
  OUTPUT_DIR: 'log/sem_seg_pointnet2_block'
  CONSISTENCY_LOSS: true
  CONSISTENCY_WEIGHTS:
    - 0.05
    - 0.05
    - 0.05
    - 0.05
  LOSS_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  SETTING:
    #SGPN
    MARGIN_SAME: 10.
    MARGIN_DIFF: 80.
    #Pointnet2
    RADIUS:
      - 0.5
      - 1.0
      - 2.0
      - 4.0


DEVICES:
  GPU_ID:
    - 1

